---
- name: Set the download url if amphora_url provided
  set_fact:
    download_url: "{{ amphora_url }}"
  when:
    amphora_url is defined and ((amphora_url | length) > 0)

- name: Set the download url to specified release branch if amphora_url not provided
  set_fact:
    download_url: "https://images.rdoproject.org/octavia/{{ release }}/amphora-x64-haproxy-centos.qcow2"
  when:
    download_url is not defined

- name: Download the amphora
  get_url:
    url: "{{ download_url }}"
    dest: "{{ target_dir }}/amphora.qcow2"
