---
- name: Fetch tripleo containers
  command: cat "{{ container_file }}"
  register: all_containers
  changed_when: false

- name: Store tripleo containers
  set_fact:
    containers: "{{ all_containers.stdout | from_yaml }}"

- name: Filter out non-tripleo containers
  set_fact:
    non_tripleo_containers: "{{ containers.container_images | json_query('[?image_source != `tripleo`]') }}"

- name: Filter out non-tripleo containers excluding kolla image_source
  set_fact:
    non_tripleo_containers: "{{ non_tripleo_containers.container_images | json_query('[?image_source != `kolla`]') }}"
  when: release in ["train"]

- name: Store non-tripleo containers
  set_fact:
    non_tripleo_containers: "{{ non_tripleo_containers | map(attribute='imagename') | list }}"

- name: Print non-tripleo containers
  debug:
    msg: "{{ non_tripleo_containers }}"

- name: Pull non-tripleo containers to the content provider registry
  become: true
  block:

    - name: Make sure buildah is installed
      package:
        name: "buildah"
        state: present

    # NOTE(mwhahaha): use buildah because --format can only be specified with buildah push.
    # Additionally we could switch to oci, but v2v2 is what we convert on the undercloud.
    - name: Pull non-tripleo containers (ceph, alertmanager, prometheus) to the content provider registry
      shell: >
        buildah images;
        buildah pull {{ item }};
        buildah push --format=v2s2 --tls-verify=False --log-level debug {{ item }} \
          docker://{{ content_provider_registry_ip }}:{{ content_provider_registry_port }}/{{ docker_registry_namespace }}/{{ item.split('/')[-1] }};
      with_items: "{{ non_tripleo_containers }}"
      register: non_tripleo
      changed_when: false
      tags:
        - skip_ansible_lint

- name: Dump non-tripleo containers output to file
  copy:
    content: "{{ non_tripleo }}"
    dest: "{{ ansible_user_dir }}/non_tripleo_containers.log"
  when: non_tripleo is defined
