---
# Validate the deployment
- name: setup dstat performance monitoring
  hosts: overcloud
  tags:
    - overcloud-validate
  roles:
    - {role: validate-perf,
       when: validate_performance|bool and run_tempest|bool}
  ignore_errors: true

- name: validate the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: false
  roles:
    - {role: validate-simple, when: test_ping|bool}

# Execute tempest using validate-tempest against the overcloud deployment
- name: Execute tempest against the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: false
  roles:
    - {role: validate-tempest, when: tempest_config|bool or run_tempest|bool}

# Execute tempest using os_tempest against the overcloud deployment
- name: Validate the deployment
  hosts: undercloud
  tasks:
    - include_tasks: tempest.yml
      vars:
        tempest_install_method: distro
        tempest_cloud_name: 'overcloud'
      when:
        - not run_tempest|bool
        - use_os_tempest is defined
        - use_os_tempest|bool
  tags:
    - overcloud-validate

# Ensure services and containers are OK
- name: Execute simple service and container validations
  hosts:
    - undercloud
    - overcloud
  tags:
    - overcloud-validate
    - undercloud-validate
  gather_facts: false
  roles:
    - {role: validate-services, when: validate_services|default(false)|bool}
